"""
lib/dataset2/partial_season_canonical.py

Family #9 canonicalization PREREQUISITE -- approved 2026-07
(research/dataset2/CANONICAL_TABLE_PROPOSAL_2026_07.md), before any
Dataset 2 canonical predictor table itself exists. Closes the two
real, disclosed gaps that proposal found:

1. GRAIN: every lib.dataset2.partial_season_traits builder that varies
   by window_n (4/6/8) and/or (position, metric_name) returns MULTIPLE
   rows per (season, player_id). build_family9_observation_wide()
   PIVOTS every one of those into a single WIDE row per (season,
   player_id), with window_n/split-type/metric_name/role-basis/tier
   encoded directly in each canonical column NAME (see
   _canonical_prefix() below), never left as a separate
   row-identifying column.

2. LAG: partial_season_traits.py itself has ZERO lag_join() calls --
   grepped directly, confirmed absent -- every one of its outputs
   describes the OBSERVATION season's own in-season split (e.g. "the
   player's final 4 games of season N"), never a preseason predictor
   for season N. build_family9_observation_wide() preserves that raw,
   same-season computation UNCHANGED (still season-N-describes-
   season-N -- this is the "raw observation-season output" the
   canonical-table proposal said must be kept). build_family9_preseason_features()
   is a SEPARATE, later step: a direct, ROW-FOR-ROW relabeling of
   every observation row from its own `season` (renamed
   `observation_season`) to `prediction_season = observation_season +
   1`. It is deliberately NOT a re-aggregation or a population lookup
   -- every output row is sourced from exactly one input row, so a
   mutation to one observation row can only ever change the ONE
   preseason row it maps to. See
   tests/test_dataset2_partial_season_canonical.py's TestLagLeakage
   for the direct proof.

NAMING: every canonical column is
`fam9_{basis}_{window_or_split}[_{position}_{metric}]_{field}`, with
`basis` in {"team", "active"}. E.g.
`fam9_team_final_4_rb_rushing_meaningful_role`,
`fam9_active_final_6_qb_passing_role_present`,
`fam9_team_final_4_wr_snap_offense_snap_share`,
`fam9_team_first_half_points_per_team_game`. The exact (raw_column ->
canonical_column) mapping is a real, generated BYPRODUCT of
build_family9_observation_wide()'s own construction loop (returned as
this function's second output) -- there is no separate, hand-written
copy of that mapping to drift out of sync with the actual renaming
code.

BOOLEAN NORMALIZATION: every boolean-shaped canonical column is cast
to pandas' nullable "boolean" dtype. TEAM-GAME-basis boolean columns
are ADDITIONALLY masked to <NA> wherever the canonical
`fam9_team_game_window_status` is not APPLICABLE -- a real, disclosed
fix for a real bug class found while writing the canonical-table
proposal: partial_season_traits.py's own `>=` threshold comparisons
against a real NaN (`team_final_n_games`/`team_final_n_active_games`
for a non-applicable row) silently evaluate to `False`, not NaN (a
real numpy/pandas comparison quirk, not a deliberate design choice in
that module), so several of ITS OWN output flags currently read as a
confident "False" for a player whose team-game window could not even
be resolved (traded, no team evidence, etc.). This module fixes that
at the canonical layer without changing partial_season_traits.py
itself. ACTIVE-GAME-basis boolean columns are NOT status-masked the
same way: `active_final_n_games == 0` is a REAL, KNOWN fact (this
player had zero real games this season), not a comparison-against-NaN
artifact -- False there is correct and stays False, verified directly
in TestBooleanNormalization.

`opportunity_qualified` (present on several raw outputs, always the
literal string `"pending"` -- see partial_season_traits.py's own
docstring) is deliberately EXCLUDED from the canonical pivot: it
carries no real information today and would sit misleadingly next to
the real, populated role-tier flags this module DOES carry through.
`team_game_window_status`/`team_final_n_games`/`team_final_n_active_games`/
`active_final_n_games` are likewise dropped from every position/metric
-scoped efficiency, role, and snap-share piece before merging -- they
are REDUNDANT with the same real values already carried once, from
the base final-N call, under `fam9_team_game_window_status` and the
window's own `fam9_{basis}_final_{n}_games`/`_active_games` columns
(verified these are computed identically regardless of position/
metric scoping, since they only ever depend on `weekly_player`, never
on which position was requested).

TEST SCOPE: tests/test_dataset2_partial_season_canonical.py proves
grain (no duplicate keys, no column-name collisions), lag/leakage
(observation-season mutation isolation, rookie nulls, the final-
historical-season future-row case), and boolean-normalization
correctness against synthetic fixtures.
"""

import sys
from pathlib import Path

import pandas as pd

sys.path.append(str(Path(__file__).resolve().parent.parent.parent))
from config import (
    DATASET2_ROLE_THRESHOLDS_ACTIVE_GAME,
    DATASET2_ROLE_THRESHOLDS_SNAP_SHARE,
    DATASET2_ROLE_THRESHOLDS_TEAM_GAME,
)
from lib.dataset2.common import validate_columns
from lib.dataset2.partial_season_traits import (
    EFFICIENCY_METRICS,
    TEAM_GAME_STATUS_APPLICABLE,
    build_active_game_efficiency_traits,
    build_active_game_final_n_traits,
    build_active_game_role_traits,
    build_team_game_efficiency_traits,
    build_team_game_final_n_traits,
    build_team_game_half_split_traits,
    build_team_game_role_traits,
    build_team_game_snap_share_role_traits,
)

DEFAULT_WINDOW_NS = (4, 6, 8)

BASIS_TEAM = "team"
BASIS_ACTIVE = "active"

CANONICAL_STATUS_COLUMN = "fam9_team_game_window_status"
CANONICAL_OUTCOME_PENDING_COLUMN = "fam9_prediction_season_outcome_unavailable"

# Raw-output field names (with the raw team_final_n_/active_final_n_/
# first_half_/second_half_ prefix already stripped) per builder kind --
# see module docstring for the exact OUTPUT_COLUMNS this was verified
# against. Kept as explicit, hardcoded lists rather than derived by
# string-stripping a raw column name, so a future rename inside
# partial_season_traits.py fails loud here (a missing/renamed raw
# column raises a real KeyError) instead of silently mismatching.
_TEAM_FINAL_N_FIELDS = (
    "games",
    "active_games",
    "points_per_team_game",
    "points_per_active_game",
    "sample_qualified_primary",
    "sample_qualified_sensitivity",
)
_TEAM_FINAL_N_BOOL_FIELDS = ("sample_qualified_primary", "sample_qualified_sensitivity")

_ACTIVE_FINAL_N_FIELDS = ("games", "games_ppg", "sample_qualified_primary", "sample_qualified_sensitivity")
_ACTIVE_FINAL_N_BOOL_FIELDS = ("sample_qualified_primary", "sample_qualified_sensitivity")

_HALF_FIELDS = (
    "team_games",
    "active_games",
    "points_per_team_game",
    "points_per_active_game",
    "sample_qualified_primary",
    "sample_qualified_sensitivity",
)
_HALF_BOOL_FIELDS = ("sample_qualified_primary", "sample_qualified_sensitivity")

_EFFICIENCY_FIELDS = (
    "opportunity",
    "production",
    "efficiency_rate",
    "efficiency_volume_eligible_exploratory",
    "efficiency_volume_eligible_sensitivity",
)
_EFFICIENCY_BOOL_FIELDS = ("efficiency_volume_eligible_exploratory", "efficiency_volume_eligible_sensitivity")

# "opportunity" is deliberately EXCLUDED here -- it is the exact same
# real value (same source column, same _aggregate_team_window sum) as
# the efficiency piece's own `..._opportunity` column for the same
# (position, metric_name, window, basis), and every (position,
# metric_name) key this module loops over for role team-game/active-
# game is a SUBSET of / identical to EFFICIENCY_METRICS's own key set
# (verified: DATASET2_ROLE_THRESHOLDS_TEAM_GAME's 4 keys and
# DATASET2_ROLE_THRESHOLDS_ACTIVE_GAME's 5 keys are both already
# covered by EFFICIENCY_METRICS's 5 keys) -- so the efficiency loop,
# which always runs alongside the role loop in
# build_family9_observation_wide(), already provides this real count
# under the same canonical name. Re-including it here would be a real
# canonical column-name collision (two different raw columns, same
# real value, fighting over one name), not new information.
_ROLE_TEAM_FIELDS = ("opportunity_per_team_game", "role_present", "meaningful_role", "strong_lead_role")
_ROLE_ACTIVE_FIELDS = ("opportunity_per_active_game", "role_present", "meaningful_role", "strong_lead_role")
_ROLE_BOOL_FIELDS = ("role_present", "meaningful_role", "strong_lead_role")

_SNAP_FIELDS = (
    "offense_snaps",
    "team_offense_total",
    "has_snap_coverage",
    "offense_snap_share",
    "role_present",
    "meaningful_role",
    "strong_lead_role",
)
_SNAP_BOOL_FIELDS = ("has_snap_coverage", "role_present", "meaningful_role", "strong_lead_role")


def _canonical_prefix(basis: str, window_or_split: str, position: str = None, metric_name: str = None) -> str:
    """`fam9_{basis}_{window_or_split}[_{position}[_{metric_name}|_snap]]_`
    -- see module docstring's NAMING section. `position` with no
    `metric_name` means the snap-share family (no metric dimension,
    only a position one)."""
    parts = [f"fam9_{basis}_{window_or_split}"]
    if position is not None:
        seg = position.lower()
        seg = f"{seg}_{metric_name}" if metric_name is not None else f"{seg}_snap"
        parts.append(seg)
    return "_".join(parts) + "_"


def _extract(df: pd.DataFrame, raw_prefix: str, fields: tuple, canonical_prefix: str, bool_fields: tuple):
    """One raw builder-output DataFrame -> (renamed df keyed on
    season/player_id, list of {raw_column, canonical_column} mapping
    rows, list of canonical boolean-shaped column names)."""
    out = df[["season", "player_id"]].copy()
    mapping_rows = []
    for field in fields:
        raw_col = f"{raw_prefix}{field}"
        canon_col = f"{canonical_prefix}{field}"
        out[canon_col] = df[raw_col]
        mapping_rows.append({"raw_column": raw_col, "canonical_column": canon_col})
    bool_cols = [f"{canonical_prefix}{f}" for f in bool_fields]
    return out, mapping_rows, bool_cols


def build_family9_observation_wide(
    population: pd.DataFrame,
    weekly_player: pd.DataFrame,
    weekly_all_positions: pd.DataFrame,
    raw_snaps: pd.DataFrame = None,
    window_ns=DEFAULT_WINDOW_NS,
):
    """
    RAW, SAME-SEASON pivot of every family #9 builder -- one row per
    (season, player_id), every window_n/(position, metric_name)/basis
    combination encoded as a distinct, canonically-named column (see
    module docstring). This is the "raw observation-season output"
    layer -- `season` here still describes the season the underlying
    partial-season split itself happened in, NOT a preseason
    predictor season. Use build_family9_preseason_features() on this
    function's own output for that.

    `raw_snaps` is optional (default None) -- when omitted, the
    offensive-snap-share role family is skipped entirely (no
    `fam9_*_snap_*` columns produced), e.g. for a population/season
    range predating real Source B coverage.

    Returns (observation_wide, column_mapping): `column_mapping` is a
    real DataFrame of every {raw_column, canonical_column} pair used
    to build `observation_wide`, generated as a byproduct of this same
    construction loop -- see module docstring's NAMING section for why
    this is never a separately hand-maintained list.

    Raises RuntimeError if two canonical columns ever collide on the
    same name (a real bug this function actively guards against, not
    assumed impossible).
    """
    validate_columns(population, ("season", "player_id", "position"), "population")

    base = population[["season", "player_id", "position"]].drop_duplicates(subset=["season", "player_id"]).reset_index(
        drop=True
    )

    pieces = []
    team_bool_cols = []
    active_bool_cols = []
    mapping_rows = []
    status_captured = False

    for n in window_ns:
        window_label = f"final_{n}"

        team_final = build_team_game_final_n_traits(population, weekly_player, weekly_all_positions, n=n)
        if not status_captured:
            status_df = team_final[["season", "player_id", "team_game_window_status"]].rename(
                columns={"team_game_window_status": CANONICAL_STATUS_COLUMN}
            )
            pieces.append(status_df)
            mapping_rows.append({"raw_column": "team_game_window_status", "canonical_column": CANONICAL_STATUS_COLUMN})
            status_captured = True

        prefix = _canonical_prefix(BASIS_TEAM, window_label)
        out, mp, bcols = _extract(team_final, "team_final_n_", _TEAM_FINAL_N_FIELDS, prefix, _TEAM_FINAL_N_BOOL_FIELDS)
        pieces.append(out)
        mapping_rows += mp
        team_bool_cols += bcols

        active_final = build_active_game_final_n_traits(population, weekly_player, n=n)
        prefix = _canonical_prefix(BASIS_ACTIVE, window_label)
        out, mp, bcols = _extract(
            active_final, "active_final_n_", _ACTIVE_FINAL_N_FIELDS, prefix, _ACTIVE_FINAL_N_BOOL_FIELDS
        )
        pieces.append(out)
        mapping_rows += mp
        active_bool_cols += bcols

        for position, metric_name in EFFICIENCY_METRICS:
            team_eff = build_team_game_efficiency_traits(
                population, weekly_player, weekly_all_positions, n=n, position=position, metric_name=metric_name
            )
            prefix = _canonical_prefix(BASIS_TEAM, window_label, position, metric_name)
            out, mp, bcols = _extract(team_eff, "team_final_n_", _EFFICIENCY_FIELDS, prefix, _EFFICIENCY_BOOL_FIELDS)
            pieces.append(out)
            mapping_rows += mp
            team_bool_cols += bcols

            active_eff = build_active_game_efficiency_traits(
                population, weekly_player, n=n, position=position, metric_name=metric_name
            )
            prefix = _canonical_prefix(BASIS_ACTIVE, window_label, position, metric_name)
            out, mp, bcols = _extract(active_eff, "active_final_n_", _EFFICIENCY_FIELDS, prefix, _EFFICIENCY_BOOL_FIELDS)
            pieces.append(out)
            mapping_rows += mp
            active_bool_cols += bcols

        for position, metric_name in DATASET2_ROLE_THRESHOLDS_TEAM_GAME:
            team_role = build_team_game_role_traits(
                population, weekly_player, weekly_all_positions, n=n, position=position, metric_name=metric_name
            )
            prefix = _canonical_prefix(BASIS_TEAM, window_label, position, metric_name)
            out, mp, bcols = _extract(team_role, "team_final_n_", _ROLE_TEAM_FIELDS, prefix, _ROLE_BOOL_FIELDS)
            pieces.append(out)
            mapping_rows += mp
            team_bool_cols += bcols

        for position, metric_name in DATASET2_ROLE_THRESHOLDS_ACTIVE_GAME:
            active_role = build_active_game_role_traits(
                population, weekly_player, n=n, position=position, metric_name=metric_name
            )
            prefix = _canonical_prefix(BASIS_ACTIVE, window_label, position, metric_name)
            out, mp, bcols = _extract(active_role, "active_final_n_", _ROLE_ACTIVE_FIELDS, prefix, _ROLE_BOOL_FIELDS)
            pieces.append(out)
            mapping_rows += mp
            active_bool_cols += bcols

        if raw_snaps is not None:
            for position in DATASET2_ROLE_THRESHOLDS_SNAP_SHARE:
                snap_role = build_team_game_snap_share_role_traits(
                    population, weekly_player, weekly_all_positions, raw_snaps, n=n, position=position
                )
                prefix = _canonical_prefix(BASIS_TEAM, window_label, position, None)
                out, mp, bcols = _extract(snap_role, "team_final_n_", _SNAP_FIELDS, prefix, _SNAP_BOOL_FIELDS)
                pieces.append(out)
                mapping_rows += mp
                team_bool_cols += bcols

    half = build_team_game_half_split_traits(population, weekly_player, weekly_all_positions)
    for raw_prefix, split_label in (("first_half_", "first_half"), ("second_half_", "second_half")):
        prefix = _canonical_prefix(BASIS_TEAM, split_label)
        out, mp, bcols = _extract(half, raw_prefix, _HALF_FIELDS, prefix, _HALF_BOOL_FIELDS)
        pieces.append(out)
        mapping_rows += mp
        team_bool_cols += bcols

    out = base
    for piece_df in pieces:
        # Checked BEFORE merging, not after: pandas' own merge() silently
        # renames a colliding column to `_x`/`_y` rather than raising,
        # which would make a post-merge duplicate-column check never
        # actually fire. A real collision here means two different raw
        # columns are fighting over one canonical name -- a bug in this
        # module's own field lists, not something to silently rename
        # around.
        incoming = set(piece_df.columns) - {"season", "player_id"}
        collisions = incoming & set(out.columns)
        if collisions:
            raise RuntimeError(
                f"Canonical column-name collision(s) detected while building "
                f"family #9's observation-wide table: {sorted(collisions)}. "
                f"Refusing to silently overwrite one canonical column with "
                f"another."
            )
        out = out.merge(piece_df, on=["season", "player_id"], how="left")

    applicable_mask = out[CANONICAL_STATUS_COLUMN] == TEAM_GAME_STATUS_APPLICABLE
    for col in team_bool_cols:
        out[col] = out[col].astype("boolean")
        out.loc[~applicable_mask, col] = pd.NA
    for col in active_bool_cols:
        out[col] = out[col].astype("boolean")

    column_mapping = pd.DataFrame(mapping_rows)
    return out.reset_index(drop=True), column_mapping


def build_family9_preseason_features(observation_wide: pd.DataFrame) -> pd.DataFrame:
    """
    THE LAG STEP -- the separate preseason-facing layer
    build_family9_observation_wide() itself deliberately does not
    build. A direct, ROW-FOR-ROW relabeling: every real observation
    row's own `season` becomes `observation_season`, and
    `prediction_season = observation_season + 1` -- every trait
    column's real value is carried through UNCHANGED, only the season
    label under which it's keyed changes. This is NOT a population
    lookup or a re-aggregation (contrast with
    lib.dataset2.common.lag_join(), which looks up a DIFFERENT row at
    season-lag for a given target row) -- there is no "target
    population" here, every real observation produces exactly one
    preseason row, including the most recent real observation season
    (see `fam9_prediction_season_outcome_unavailable` below).

    Because each output row is sourced from exactly one input row,
    mutating one observation-season row can only ever change the ONE
    preseason row it maps to -- see
    tests/test_dataset2_partial_season_canonical.py's TestLagLeakage
    for the direct proof this holds.

    A player with NO real observation row for a given season (a
    rookie, or any season a player has no family #9 data for) simply
    has no row here for that season -- left-joining this output onto a
    target scoring population (the caller's responsibility, same
    "caller scopes population" convention as every other Dataset 2
    module) naturally produces null, never a zero, for every fam9_*
    column on that population row.

    `fam9_prediction_season_outcome_unavailable` is True exactly when
    `prediction_season` exceeds the max real `observation_season`
    present in `observation_wide` -- i.e., the row's predictors are
    real (built from the most recent real historical season), but no
    outcome for `prediction_season` exists yet to attach. Computed
    dynamically from the input's own real season range, never a
    hardcoded year.
    """
    validate_columns(observation_wide, ("season", "player_id"), "observation_wide")
    working = observation_wide.drop_duplicates(subset=["season", "player_id"]).reset_index(drop=True)

    max_observed_season = working["season"].max()

    out = working.rename(columns={"season": "observation_season"})
    out["prediction_season"] = out["observation_season"] + 1
    out[CANONICAL_OUTCOME_PENDING_COLUMN] = out["prediction_season"] > max_observed_season

    id_cols = ["prediction_season", "observation_season", "player_id"]
    ordered = id_cols + [c for c in out.columns if c not in id_cols]
    return out[ordered].reset_index(drop=True)
