"""
player_matching.py

Priority 4: deterministic player identity matching between the clean
ADP table (from 02_clean_adp.py) and the nflverse season-results table
(from 03_download_stats.py), plus a persistent override table for the
cases that will never match algorithmically.

This is a library module, not a numbered pipeline step -- it's meant
to be imported by 04_build_master_dataset.py (Priority 5). It's also
directly runnable for standalone testing/validation, which is how it
was verified before being wired into anything else.

Matching strategy, in priority order (first match wins):
  1. Manual override table (data/manual/player_name_overrides.csv) --
     always checked first. A human said "this ADP name in this season
     is this nflverse player_id," full stop, no further guessing.
  2. Exact match on (season, normalized_name, position).
  3. Exact match on (season, normalized_name) alone, position
     mismatched -- still auto-matched, but flagged into the
     low-confidence report for review (a position discrepancy between
     sources is a real signal something might be off, even if the name
     match is solid).
  4. Fuzzy match (rapidfuzz) within (season, position), using
     normalized names. >=92 auto-matches; 80-91 auto-matches but is
     ALSO written to the low-confidence report; <80 is left unmatched.
  5. No match at any stage -> missing_adp_matches.

Duplicate handling: if step 2 or 3 finds MORE than one candidate
(genuine name collision within a season/position), the ADP row is
NOT auto-matched -- it goes to duplicate_player_matches for a human to
resolve via the override table, rather than picking one arbitrarily.

Positions out of v1.0 scope (anything not QB/RB/WR/TE -- e.g. team
defenses, kickers) are filtered out of the ADP table before matching
even starts, and logged separately. These are not "missing matches"
in the concerning sense -- nflverse's results table never had them to
begin with, by design (see 03_download_stats.py). Conflating them with
genuine missing matches would make the validation report misleading.

Input:  data/processed/adp_clean_<start>_<end>.csv  (from 02)
        data/raw/nflverse/season_results_ppr_<start>_<end>.csv (from 03)
        data/manual/player_name_overrides.csv (optional, hand-maintained)
Output: data/processed/player_matches.csv
        data/exports/validation/missing_adp_matches.csv
        data/exports/validation/low_confidence_player_matches.csv
        data/exports/validation/duplicate_player_matches.csv
"""

import re
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parent.parent))

import pandas as pd
from rapidfuzz import fuzz

SKILL_POSITIONS = {"QB", "RB", "WR", "TE"}

FUZZY_AUTO_MATCH_THRESHOLD = 92
FUZZY_REVIEW_FLOOR = 80

PAREN_TAG_RE = re.compile(r"\s*\([^)]*\)\s*$")
WHITESPACE_RE = re.compile(r"\s+")
SUFFIX_RE = re.compile(r"\b(jr|sr|ii|iii|iv)\b\.?", re.IGNORECASE)

OVERRIDE_PATH = Path("data/manual/player_name_overrides.csv")


def normalize_name(raw_name: str) -> str:
    """Same base normalization as 02_clean_adp.py, PLUS generational
    suffix stripping (Jr/Sr/II/III/IV) -- these are pure noise for
    identity matching (same person) but were dragging otherwise-clean
    matches into the fuzzy-review pile unnecessarily (e.g. 'Robert
    Griffin III' vs nflverse's 'Robert Griffin' was only scoring 87.5%
    fuzzy before this). NOTE: 02_clean_adp.py's normalize_name does
    NOT have this suffix-stripping step -- that's intentional, not a
    bug: this module's normalization is used only for matching/
    comparison, while 02's is used for the canonical
    player_name_normalized field stored in the clean ADP output, where
    preserving 'Jr.'/'III' etc. as written is more useful for a human
    reading that table."""
    name = str(raw_name).strip()
    name = PAREN_TAG_RE.sub("", name)
    name = WHITESPACE_RE.sub(" ", name)
    name = name.replace(".", "")
    name = name.strip().lower()
    name = SUFFIX_RE.sub("", name)
    name = WHITESPACE_RE.sub(" ", name)
    return name.strip()


def load_overrides() -> pd.DataFrame:
    """
    Persistent override table. Columns:
      season, adp_player_name_original, position, nflverse_player_id, notes
    Created empty with headers if it doesn't exist yet -- this file is
    meant to be hand-edited over time as review reports surface real
    cases, not regenerated by any script.
    """
    if OVERRIDE_PATH.exists():
        return pd.read_csv(OVERRIDE_PATH, dtype=str)

    OVERRIDE_PATH.parent.mkdir(parents=True, exist_ok=True)
    empty = pd.DataFrame(columns=[
        "season", "adp_player_name_original", "position",
        "nflverse_player_id", "notes",
    ])
    empty.to_csv(OVERRIDE_PATH, index=False)
    print(f"No override table found -- created an empty one at {OVERRIDE_PATH}")
    return empty


def match_players(adp_df: pd.DataFrame, results_df: pd.DataFrame,
                   overrides_df: pd.DataFrame = None):
    """
    Returns (matched_df, missing_df, low_confidence_df, duplicates_df,
    out_of_scope_df).
    """
    if overrides_df is None:
        overrides_df = load_overrides()

    # -- filter ADP to v1.0 scope before matching even starts --
    out_of_scope = adp_df[~adp_df["position"].isin(SKILL_POSITIONS)].copy()
    adp_scoped = adp_df[adp_df["position"].isin(SKILL_POSITIONS)].copy()

    # -- prep results side --
    results = results_df.copy()
    results["name_normalized"] = results["player_display_name"].apply(normalize_name)

    # -- prep override lookup: (season, normalized original name) -> player_id --
    override_lookup = {}
    if not overrides_df.empty:
        for _, r in overrides_df.iterrows():
            key = (str(r["season"]), normalize_name(r["adp_player_name_original"]))
            override_lookup[key] = r["nflverse_player_id"]

    matched_rows = []
    missing_rows = []
    low_confidence_rows = []
    duplicate_rows = []

    for _, adp_row in adp_scoped.iterrows():
        season = adp_row["season"]
        # IMPORTANT: re-normalize here using THIS module's normalize_name
        # (which strips Jr/Sr/II/III/IV), not the player_name_normalized
        # column already baked into adp_df by 02_clean_adp.py (which
        # deliberately does NOT strip suffixes -- see the docstring on
        # normalize_name above). Comparing against a mismatched
        # normalization would silently break exact matching for every
        # suffixed name.
        name_norm = normalize_name(adp_row["player_name_original"])
        position = adp_row["position"]

        # 1. override table
        override_key = (str(season), name_norm)
        if override_key in override_lookup:
            matched_rows.append({
                **adp_row.to_dict(),
                "nflverse_player_id": override_lookup[override_key],
                "match_type": "manual_override",
                "match_confidence": 100,
            })
            continue

        season_pool = results[results["season"] == season]

        # 2. exact name + position
        exact_pos = season_pool[
            (season_pool["name_normalized"] == name_norm)
            & (season_pool["position"] == position)
        ]
        if len(exact_pos) == 1:
            matched_rows.append({
                **adp_row.to_dict(),
                "nflverse_player_id": exact_pos.iloc[0]["player_id"],
                "match_type": "exact_name_position",
                "match_confidence": 100,
            })
            continue
        if len(exact_pos) > 1:
            duplicate_rows.append({
                **adp_row.to_dict(),
                "candidate_player_ids": ";".join(exact_pos["player_id"].astype(str)),
                "reason": "multiple nflverse players share season+name+position",
            })
            continue

        # 3. exact name only (position mismatch)
        exact_name = season_pool[season_pool["name_normalized"] == name_norm]
        if len(exact_name) == 1:
            row = {
                **adp_row.to_dict(),
                "nflverse_player_id": exact_name.iloc[0]["player_id"],
                "match_type": "exact_name_position_mismatch",
                "match_confidence": 90,
            }
            matched_rows.append(row)
            low_confidence_rows.append({
                **row,
                "nflverse_position": exact_name.iloc[0]["position"],
                "reason": "name matched exactly but position differs from ADP source",
            })
            continue
        if len(exact_name) > 1:
            duplicate_rows.append({
                **adp_row.to_dict(),
                "candidate_player_ids": ";".join(exact_name["player_id"].astype(str)),
                "reason": "multiple nflverse players share season+name (position ignored)",
            })
            continue

        # 4. fuzzy match within season+position
        position_pool = season_pool[season_pool["position"] == position]
        best_score = -1
        best_row = None
        for _, cand in position_pool.iterrows():
            score = fuzz.ratio(name_norm, cand["name_normalized"])
            if score > best_score:
                best_score = score
                best_row = cand

        if best_row is not None and best_score >= FUZZY_AUTO_MATCH_THRESHOLD:
            matched_rows.append({
                **adp_row.to_dict(),
                "nflverse_player_id": best_row["player_id"],
                "match_type": "fuzzy_high_confidence",
                "match_confidence": best_score,
            })
            continue
        if best_row is not None and best_score >= FUZZY_REVIEW_FLOOR:
            row = {
                **adp_row.to_dict(),
                "nflverse_player_id": best_row["player_id"],
                "match_type": "fuzzy_low_confidence",
                "match_confidence": best_score,
            }
            matched_rows.append(row)
            low_confidence_rows.append({
                **row,
                "nflverse_matched_name": best_row["player_display_name"],
                "reason": f"fuzzy match below auto-confidence threshold ({best_score})",
            })
            continue

        # 5. no match at any stage
        missing_rows.append({
            **adp_row.to_dict(),
            "best_fuzzy_score": best_score if best_row is not None else None,
            "closest_candidate": best_row["player_display_name"] if best_row is not None else None,
            "reason": "no override, no exact match, fuzzy score below review floor",
        })

    matched_df = pd.DataFrame(matched_rows)
    missing_df = pd.DataFrame(missing_rows)
    low_confidence_df = pd.DataFrame(low_confidence_rows)
    duplicates_df = pd.DataFrame(duplicate_rows)

    return matched_df, missing_df, low_confidence_df, duplicates_df, out_of_scope


def main():
    adp_path = Path("data/processed/adp_clean_2006_2025.csv")
    results_path = Path("data/raw/nflverse/season_results_ppr_2006_2025.csv")

    if not adp_path.exists() or not results_path.exists():
        raise FileNotFoundError(
            "player_matching.py needs both 02_clean_adp.py's output and "
            "03_download_stats.py's output to exist first. Run those steps."
        )

    adp_df = pd.read_csv(adp_path)
    results_df = pd.read_csv(results_path)
    overrides_df = load_overrides()

    matched, missing, low_conf, dupes, out_of_scope = match_players(
        adp_df, results_df, overrides_df
    )

    validation_dir = Path("data/exports/validation")
    validation_dir.mkdir(parents=True, exist_ok=True)
    processed_dir = Path("data/processed")
    processed_dir.mkdir(parents=True, exist_ok=True)

    matched.to_csv(processed_dir / "player_matches.csv", index=False)
    missing.to_csv(validation_dir / "missing_adp_matches.csv", index=False)
    low_conf.to_csv(validation_dir / "low_confidence_player_matches.csv", index=False)
    dupes.to_csv(validation_dir / "duplicate_player_matches.csv", index=False)
    out_of_scope.to_csv(validation_dir / "out_of_scope_adp_rows.csv", index=False)

    total_scoped = len(adp_df) - len(out_of_scope)
    match_rate = len(matched) / total_scoped * 100 if total_scoped else 0

    print(f"Total ADP rows: {len(adp_df)}")
    print(f"Out of v1.0 scope (not QB/RB/WR/TE, excluded before matching): {len(out_of_scope)}")
    print(f"In-scope rows attempted: {total_scoped}")
    print(f"Matched: {len(matched)} ({match_rate:.1f}%)")
    print(f"  - manual_override: {(matched['match_type'] == 'manual_override').sum() if len(matched) else 0}")
    print(f"  - exact_name_position: {(matched['match_type'] == 'exact_name_position').sum() if len(matched) else 0}")
    print(f"  - exact_name_position_mismatch: {(matched['match_type'] == 'exact_name_position_mismatch').sum() if len(matched) else 0}")
    print(f"  - fuzzy_high_confidence: {(matched['match_type'] == 'fuzzy_high_confidence').sum() if len(matched) else 0}")
    print(f"  - fuzzy_low_confidence: {(matched['match_type'] == 'fuzzy_low_confidence').sum() if len(matched) else 0}")
    print(f"Missing (no match found): {len(missing)}")
    print(f"Low-confidence (needs human review): {len(low_conf)}")
    print(f"Duplicates (needs override table entry): {len(dupes)}")

    return matched, missing, low_conf, dupes, out_of_scope


if __name__ == "__main__":
    main()
